version: '3'

services:
  autophrase:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        repo: https://github.com/Katsumata420/AutoPhrase
        branch: japanese
    environment:
      RAW_TRAIN: ${TRAIN_DATA:-data/input.txt}
      ENABLE_POS_TAGGING: 1
      MIN_SUP: 30
      THREAD: 10
      MODEL: ${MODEL_PATH:-models/MyModel}
      TEXT_TO_SEG: ${TRAIN_DATA:-data/input.txt}
    volumes:
      - ./data:/autophrase/data
      - ./models:/autophrase/models
    command: bash auto_phrase.sh
